#[Info]
site_name: SDNU机器人与人工智能实验室
docs_dir: 'docs'
site_dir: 'site'
site_description: >-
  山东师范大学信息科学与工程学院机器人与人工智能实验室

repo_name: SDNURoboticsAILab.github.io
repo_url: https://github.com/SDNURoboticsAILab/SDNURoboticsAILab.github.io

copyright: Copyright &copy; 2024-present <a href="https://github.com/SDNURoboticsAILab" target="_blank" rel="noopener noreferrer">Robotics and AI Lab, SDNU</a>

#[Navigation]
nav: 
  - 介绍: index.md
  - 竞赛目录:
    - 中国机器人及人工智能大赛: contest/CRAIC.md
    - 国际青年人工智能大赛: contest/IYAIC.md
    - 机器人世界杯中国赛: contest/RoboCup-China-Open.md
    - 机器人世界杯: contest/RoboCup.md
    - 全国大学生机器人科技创新交流营暨机器人大赛: contest/Robotics-Innovation-Camp-by-CYL.md
  - 教学资源:
    - 编程基础:
      - Python语法基础:
        - Python简介: resource/programming/Python/Python_Introduction.md
      - C++语法基础:
        - C++目录: resource/programming/CPP/c-plus-plus.md
        - C++概述:
          - C++编程语言简介: resource/programming/CPP/Overview/introduction-to-c-programming-language.md
          - C++的特点: resource/programming/CPP/Overview/features-of-cpp.md
          - C++的历史: resource/programming/CPP/Overview/history-of-c.md
          - 关于C++的有趣事实: resource/programming/CPP/Overview/interesting-facts-about-c.md
          - 设置 C++ 开发环境: resource/programming/CPP/Overview/setting-c-development-environment.md
          - C和C++的不同之处: resource/programming/CPP/Overview/difference-between-C-and-cpp.md
        - C++基础:
          - C++基础语法: resource/programming/CPP/Basics/cpp-basic-syntax.md
          - C++注释: resource/programming/CPP/Basics/cpp-comments.md
          - C++标识符: resource/programming/CPP/Basics/cpp-identifiers.md
          - C++关键字: resource/programming/CPP/Basics/cpp-keywords.md
          - C++标记: resource/programming/CPP/Basics/cpp-tokens.md
          - 关键字和标识符的区别: resource/programming/CPP/Basics/difference-between-keyword-and-identifier.md
          - 编写第一个C++程序: resource/programming/CPP/Basics/writing-first-c-program-hello-world-example.md
        - C++数据类型和字面量:
          - C++数据类型: resource/programming/CPP/Data-Types-and-Literals/cpp-Data-Types.md
          - C++派生数据类型: resource/programming/CPP/Data-Types-and-Literals/cpp-Derived-Data-Types.md
          - C++用户定义数据类型: resource/programming/CPP/Data-Types-and-Literals/cpp-User-Defined-Data-Types.md
          - C++类型修饰符: resource/programming/CPP/Data-Types-and-Literals/cpp-Type-Modifiers.md
          - C++数据类型范围及其宏: resource/programming/CPP/Data-Types-and-Literals/cpp-Data-Type-Ranges-and-Their-Macros.md
          - C++字面量: resource/programming/CPP/Data-Types-and-Literals/cpp-Literals.md
          - C++数据类型转换: resource/programming/CPP/Data-Types-and-Literals/cpp-Data-Type-Conversion.md
          - C++类型转换运算符: resource/programming/CPP/Data-Types-and-Literals/cpp-Typecasting-Operators.md
        - C++变量和常量:
          - C++变量: resource/programming/CPP/Variables-and-Constants/cpp-variables.md
          - C++常量: resource/programming/CPP/Variables-and-Constants/cpp-constants.md
          - C++变量作用域: resource/programming/CPP/Variables-and-Constants/scope-of-variables-in-c.md
          - C++存储类: resource/programming/CPP/Variables-and-Constants/storage-classes-in-c-with-examples.md
          - C++ static关键字: resource/programming/CPP/Variables-and-Constants/static-keyword-cpp.md
        - C++运算符:
          - C++运算符: resource/programming/CPP/Operators/cpp-operators.md
          - C++算术运算符: resource/programming/CPP/Operators/cpp-arithmetic-operators.md
          - C++关系运算符: resource/programming/CPP/Operators/cpp-relational-operators.md
          - C++逻辑运算符: resource/programming/CPP/Operators/cpp-logical-operators.md
          - C++位运算符: resource/programming/CPP/Operators/cpp-bitwise-operators.md
          - C++赋值运算符: resource/programming/CPP/Operators/cpp-assignment-operators.md
          - C++一元运算符: resource/programming/CPP/Operators/cpp-unary-operators.md
          - C++三元运算符: resource/programming/CPP/Operators/cpp-ternary-or-conditional-operators.md
          - C++ sizeof运算符: resource/programming/CPP/Operators/cpp-sizeof-operator.md
          - C++作用域解析运算符: resource/programming/CPP/Operators/cpp-scope-resolution-operator.md
        - C++输入输出:
          - C++基本输入输出: resource/programming/CPP/Input-Output/basic-input-output-c.md
          - C++ cin: resource/programming/CPP/Input-Output/cin-in-c.md
          - C++ cout: resource/programming/CPP/Input-Output/cout-in-c.md
          - C++ cerr: resource/programming/CPP/Input-Output/cerr-standard-error-stream-object-in-cpp.md
          - C++操纵符: resource/programming/CPP/Input-Output/manipulators-in-c-with-examples.md
        - C++控制语句:
          - C++决策: resource/programming/CPP/ControlStatements/cpp-decision-making.md
          - C++ if语句: resource/programming/CPP/ControlStatements/c-if-statement-with-examples.md
          - C++ if-else语句: resource/programming/CPP/ControlStatements/c-if-else-statement-with-examples.md
          - C++ if-else-if阶梯: resource/programming/CPP/ControlStatements/c-if-else-if-ladder-with-examples.md
          - C++嵌套if-else: resource/programming/CPP/ControlStatements/cpp-nested-if-else-statement.md
          - C++ switch语句: resource/programming/CPP/ControlStatements/switch-statement-in-cpp.md
          - C++循环: resource/programming/CPP/ControlStatements/cpp-loops.md
          - C++ for循环: resource/programming/CPP/ControlStatements/cpp-for-loop.md
          - C++ while循环: resource/programming/CPP/ControlStatements/cpp-while-loop.md
          - C++ do-while循环: resource/programming/CPP/ControlStatements/cpp-do-while-loop.md
          - C++基于范围的for循环: resource/programming/CPP/ControlStatements/range-based-loop-c.md
          - C++跳转语句: resource/programming/CPP/ControlStatements/jump-statements-in-c.md
        - C++函数:
          - C++函数: resource/programming/CPP/Functions/functions-in-cpp.md
          - C++参数传递技术: resource/programming/CPP/Functions/parameter-passing-techniques-in-cpp.md
          - C++按值调用和按引用调用的区别: resource/programming/CPP/Functions/difference-between-call-by-value-and-call-by-reference.md
          - C++返回语句: resource/programming/CPP/Functions/return-statement-in-cpp-with-examples.md
          - C++默认参数: resource/programming/CPP/Functions/default-arguments-c.md
          - C++内联函数: resource/programming/CPP/Functions/inline-functions-cpp.md
          - C++ Lambda表达式: resource/programming/CPP/Functions/lambda-expression-in-c.md
          - C++递归: resource/programming/CPP/Functions/cpp-recursion.md
      - 面向对象的编程:
        - 面向对象的编程简介: resource/programming/OOP/OOP_Introduction.md
    - 理论基础:
      - 数据结构与算法:
        - 数据结构与算法简介: resource/theory/Algorithm&DS/Algorithm&DS_Introduction.md
      - 线性代数相关补充:
        - 线性代数相关补充简介: resource/theory/Linear_Algebra/Linear_Algebra_Introduction.md
      - 机器人运动学:
        - 机器人运动学简介: resource/theory/Robot_Kinematics/Robot_Kinematics_Introduction.md
      - 数字图像处理(基于OpenCV C++):
        - 数字图像处理简介: resource/theory/CV/CV_Introduction.md
      - 机器学习(基于PyTorch):
        - 机器学习简介: resource/theory/Machine_Learning/Machine_Learning_Introduction.md
    - NAO机器人:
      - NAO机器人简介:
        - 基本简述: resource/NAO/Introduction/Basic_Introduction.md
        - 软件平台简述: resource/NAO/Introduction/Software_Platform.md
        - 硬件平台简述: resource/NAO/Introduction/Hardware_Platform.md
        - 运动学数据: resource/NAO/Introduction/Kinematics.md
        - 执行器和传感器数据: resource/NAO/Introduction/Actuators_and_Sensors.md
      - NAO机器人使用基础(基于NAOqi):
        - NAO机器人的基本操作: resource/NAO/Usage/Basic_Operations.md
        - Choregraphe控制NAO机器人简述: resource/NAO/Usage/Choregraphe_Control.md
        - Python控制NAO机器人简述: resource/NAO/Usage/Python_Control.md
        - C++控制NAO机器人简述: resource/NAO/Usage/Cpp_Control.md
      - NAOqi APIs简述:
        - NAOqi Core: resource/NAO/APIs/NAOqi_Core.md
        - NAOqi Emotion: resource/NAO/APIs/NAOqi_Emotion.md
        - NAOqi Interaction engines: resource/NAO/APIs/NAOqi_Interaction.md
        - NAOqi Motion: resource/NAO/APIs/NAOqi_Motion.md
        - NAOqi Audio: resource/NAO/APIs/NAOqi_Audio.md
        - NAOqi Vision: resource/NAO/APIs/NAOqi_Vision.md
        - NAOqi People Perception: resource/NAO/APIs/NAOqi_People_Perception.md
        - NAOqi Sensors & LEDs: resource/NAO/APIs/NAOqi_Sensors_and_LEDs.md
    - 实用软件基础:
      - Git版本控制系统:
        - GNU Make编译工具简介: resource/software/GNU_Make/GNU_Make_Introduction.md
      - Linux指令基础:
        - Linux指令基础简介: resource/software/Linux/Linux_Introduction.md
      - Git版本控制:
      - GNU Make编译工具:
        - GNU Make编译工具简介: resource/software/GNU_Make/GNU_Make_Introduction.md
      - CMake编译工具:
        - CMake编译工具简介: resource/software/CMake/CMake_Introduction.md
      - GDB调试工具:
        - GDB调试工具简介: resource/software/GDB/GDB_Introduction.md
      - LaTeX:
      - Docker:
        - Docker简介: resource/software/Docker/Docker_Introduction.md
      - Misc:
        - 2024级技术部第0节课: resource/software/Misc/2024-tech-lesson0.md
  - 培养计划:
    - 必读: plan/introduction.md
    - 第一阶段: plan/training_plan_1.md
    - 第二阶段: plan/training_plan_2.md
    - 第三阶段: plan/training_plan_3.md
    - 第四阶段: plan/training_plan_4.md
  - 成员风采:
    - 竞赛一览:
      - 2023年: memberStyle/Competition_Chronicles/2023.md
      - 2024年: memberStyle/Competition_Chronicles/2024.md
      - 2025年: memberStyle/Competition_Chronicles/2025.md
    - 日常印记:
      - 2023年: memberStyle/Daily_Echos/2023.md
      - 2024年: memberStyle/Daily_Echos/2024.md
      - 2025年: memberStyle/Daily_Echos/2025.md
  - 历届获奖:
    - 中国机器人及人工智能大赛:
      - 获奖情况: awards/CRAIC.md
      - 2023 年获奖证书: awards/CRAIC-2023.md
      - 2024 年获奖证书: awards/CRAIC-2024.md
    - 机器人世界杯中国赛:
      - 获奖情况: awards/RoboCup-China-Open.md
      - 2024 年获奖证书: awards/RoboCup-China-Open-2024.md
      - 2025 年获奖证书: awards/RoboCup-China-Open-2025.md
    - 全国大学生机器人科技创新交流营暨机器人大赛:
      - 获奖情况: awards/Robotics-Innovation-Camp-by-CYL.md
      - 2023 年获奖证书: awards/Robotics-Innovation-Camp-by-CYL-2023.md
    - 国际青年人工智能大赛:
      - 获奖情况: awards/IYAIC.md
      - 2023 年获奖证书: awards/IYAIC-2023.md
      - 2024 年获奖证书: awards/IYAIC-2024.md
    - 山东省高校机器人大赛:
      - 获奖情况: awards/Shandong-Provincial-University-Contest-on-Intelligent-Robotic-Innovations.md
      - 2022 年获奖证书: awards/Shandong-Provincial-University-Contest-on-Intelligent-Robotic-Innovations-2022.md
    - 浪曦杯机器人编程大赛:
      - 获奖情况: awards/Robocode.md
      - 2023 年获奖证书: awards/Robocode-2023.md
      - 2024 年获奖证书: awards/Robocode-2024.md
  - 产品介绍:
    - 教学培训:
      - 网络安全培训: products/Teach/Network-security/Network.md
      - 机器人编程培训: products/Teach/robot/robot.md
      - 信息学算法培训: products/Teach/Algorithm/Algorithm.md
      - 机器学习方向研发培训: products/Teach/Learn/Learn.md
    - 网页/小程序开发: products/Web/Web.md
    - 视觉:
      - 目标识别: products/CV/Object/Object.md
      - 人脸识别:  products/CV/Face/Face.md  #(活体检测，人脸属性分析，人脸检测)
    - 大模型:
      - 代码生成: others/doing.md
      - 文档生成: others/doing.md 
      - 图像生成: others/doing.md
    - 虚拟技术:
      - AI虚拟人: products/Virtual/People/People.md
      - AI虚拟声音: products/Virtual/Sound/Sound.md   # add VR & AR
    - 数据挖掘/数据处理: products/Data/Data.md
    - 私人定制业务: products/Custom-made/Custom.md
  - 商业合作:
    - 商业合作: commercial/commercial.md
  - 其他:
    - 机器人实验室新媒体纳新通知: others/publicity.md
    - 机器人实验室技术部纳新通知: others/technical.md
    - 机器人实验室2023级纳新测试: others/2023test.md
    - 纳新抽奖活动: others/Sweepstakes.md
    - 如何贡献: others/htc.md
    - 有趣的东西: others/interesting.md
  

#[UI]
theme:
  name: material
  static_templates:
    - 404.html
  favicon: favicon.ico
  icon:
    logo: images/logo.png
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  features:
    - navigation.instant # 现在页面不会跳转,而是类似单页应用,搜索和各种跳转都是在当前页面完成,对美观有很大帮助
    - navigation.tabs # 页面上方的标签页
    - navigation.tracking # 页面滚动时，导航栏高亮当前页面
    - navigation.sections # 使导航栏分块
    # - navigation.expand # 默认展开导航
    # - navigation.prune # 只渲染当前页面的导航
    - toc.follow # 滚动的时候侧边栏自动跟随
    - navigation.top # 返回顶部按钮
    - search.suggest # 补全建议
    - search.highlight # 搜索结果高亮
    - navigation.footer # 页脚提示下一章
    - content.code.copy # 代码段上的赋值按钮
    - content.action.edit
    - content.action.view

  custom_dir: overrides

#[Plugins]
plugins:
  # Translation plugin
  - i18n:
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true
          site_name: Robotics and AI Lab, SDNU
          nav_translations:
            介绍: Introduction

            竞赛目录: Contest Category
            中国机器人及人工智能大赛: CRAIC
            国际青年人工智能大赛: IYAIC
            机器人世界杯中国赛: RoboCup China Open
            机器人世界杯: RoboCup
            全国大学生机器人科技创新交流营暨机器人大赛: Robotics Innovation Camp by CYL

            教学资源: Learning Resource
            编程基础: Programming Basics
            Python语法基础: Python Syntax Basics
            Python简介: Introduction to Python
            C++语法基础: C++ Syntax Basics
            C++简介: Introduction to C++
            面向对象的编程: Objective Oriented Programming, OOP
            面向对象的编程简介: Introduction to OOP
            理论基础: Theoretical Basics
            数据结构与算法: Data Structure & Algorithm
            数据结构与算法简介: Introduction
            线性代数相关补充: Linear Algebra Related Supplements
            线性代数相关补充简介: Introduction
            机器人运动学: Robot Kinematics
            机器人运动学简介: Introduction to Robot Kinematics
            数字图像处理(基于OpenCV C++): Digital Image Processing (based on OpenCV C++)
            数字图像处理简介: Introduction to Digital Image Processing
            机器学习(基于PyTorch): Machine Learning (based on PyTorch)
            机器学习简介: Introduction to ML
            NAO机器人: NAO Robot
            NAO机器人简介: Introduction to NAO
            基本简述: Basics
            软件平台简述: Software Platform
            硬件平台简述: Hardware Platform
            运动学数据: Kinematic Data
            执行器和传感器数据: Actuator and Sensor Data
            NAO机器人使用基础(基于NAOqi): NAO Robot Usage Basics (based on NAOqi)
            NAO机器人的基本操作: Basic Operations
            Choregraphe控制NAO机器人简述: Using Choregraphe to Control NAO
            Python控制NAO机器人简述: Using Python to Control NAO
            C++控制NAO机器人简述: Using C++ to Control NAO
            NAOqi APIs简述: Introduction to NAOqi APIs
            实用软件基础: Practical Software Basics
            Linux基础教程: Linux Command Basics
            Linux终端入门: Getting Started With Linux Terminal
            第1章：Linux 终端中的目录切换: Chapter 1:Changing Directories in Linux Terminal
            第2章：在 Linux 终端中创建目录: Chapter 2:Making Directories in Linux Terminal
            Git版本控制系统: Git, Version Control System
            Git秘籍: Git Cheat sheet
            GNU Make编译工具: GNU Make, Compilation Tool
            GNU Make编译工具简介: Introduction to GNU Make
            CMake编译工具: CMake, Compilation Tool
            CMake编译工具简介: Introduction to CMake
            GDB调试工具: GDB, Debugging Tool
            GDB调试工具简介: Introduction to GDB
            LaTeX简介: Introduction to LaTeX
            Docker简介: Introduction to Docker

            成员风采: Member Style
            竞赛一览: Competition Chronicles
            日常印记: Daily Echos
            2023年: 2023
            2024年: 2024

            历届获奖: Previous Awards
            获奖情况: Awards
            2023 年获奖证书: 2023 Award Certificates
            2024 年获奖证书: 2024 Award Certificates
            山东省高校机器人大赛: Shandong Provincial University Contest on Intelligent Robotic Innovations
            浪曦杯机器人编程大赛: Robocode

            其他: Others
            如何贡献: How To Contribute
            有趣的东西: Something Interesting
  # Search plugin
  - search:
      lang:
        - zh
        - en
  # Minify html, speed up the loading speed
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: SDNURoboticsAILab/SDNURoboticsAILab.github.io
      branch: master
      token: !ENV ['MKDOCS_GIT_COMMITTERS_APIKEY']
  # - git-authors

extra_javascript:
  # 使用mathjax进行数学公式渲染
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - admonition # 那些提醒
  - footnotes # 脚注
  - toc
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.arithmatex: # latex支持
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true # 显示行号
      use_pygments: true # 代码高亮
      pygments_lang_class: true # 代码高亮
      auto_title: true # 显示编程语言名称
      linenums_style: pymdownx-inline # 行号样式,防止复制的时候复制行号
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  