#[Info]
site_name: SDNU机器人与人工智能实验室
docs_dir: 'mdfile'
site_dir: 'docs'
site_description: >-
  山东师范大学信息科学与工程学院机器人与人工智能实验室

repo_name: SDNURoboticsAILab.github.io
repo_url: https://github.com/SDNURoboticsAILab/SDNURoboticsAILab.github.io

copyright: Copyright &copy; 2024-present <a href="https://github.com/SDNURoboticsAILab" target="_blank" rel="noopener noreferrer">Robotics and AI Lab, SDNU</a>

#[Navigation]
nav:
  - 介绍: index.md
  - 竞赛目录:
    - 中国机器人及人工智能大赛: contest/CRAIC.md
    - 国际青年人工智能大赛: contest/IYAIC.md
    - 机器人世界杯中国赛: contest/RoboCup China Open.md
    - 机器人世界杯: contest/RoboCup.md
    - 全国大学生机器人科技创新交流营暨机器人大赛: contest/Robotics Innovation Camp by CYL.md
    
  - 教学资源:
    - 编程基础:
      - Python语法基础:
        - Python简介: resource/programming/Python/Python_Introduction.md
      - C++语法基础:
        - C++简介: resource/programming/CPP/CPP_Introduction.md
      - 面向对象的编程:
        - 面向对象的编程简介: resource/programming/OOP/OOP_Introduction.md
    - 理论基础:
      - 数据结构与算法:
        - 数据结构与算法简介: resource/theory/Algorithm&DS/Algorithm&DS_Introduction.md
      - 线性代数相关补充:
        - 线性代数相关补充简介: resource/theory/Linear_Algebra/Linear_Algebra_Introduction.md
      - 机器人运动学:
        - 机器人运动学简介: resource/theory/Robot_Kinematics/Robot_Kinematics_Introduction.md
      - 数字图像处理(基于OpenCV C++):
        - 数字图像处理简介: resource/theory/CV/CV_Introduction.md
      - 机器学习(基于PyTorch):
        - 机器学习简介: resource/theory/Machine_Learning/Machine_Learning_Introduction.md
    - 实用软件基础:
      - Linux指令基础:
        - Linux指令基础简介: resource/software/Linux/Linux_Introduction.md
      - Git版本控制:
        - Git版本控制简介: resource/software/Git/Git_Introduction.md
      - GNU Make编译工具:
        - GNU Make编译工具简介: resource/software/GNU_Make/GNU_Make_Introduction.md
      - CMake编译工具:
        - CMake编译工具简介: resource/software/CMake/CMake_Introduction.md
      - GDB调试:
        - GDB调试简介: resource/software/GDB/GDB_Introduction.md
      - LaTeX:
        - LaTeX简介: resource/software/LaTeX/LaTeX_Introduction.md
      - Docker:
        - Docker简介: resource/software/Docker/Docker_Introduction.md
      - Misc
  - 成员风采: social/social.md
  - 历届获奖: awards/awards.md
  - 其他:
    - 有趣的东西: others/interesting.md

#[UI]
theme:
  name: material
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  icon:
    logo: images/logo.png
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  features:
    - navigation.instant # 现在页面不会跳转,而是类似单页应用,搜索和各种跳转都是在当前页面完成,对美观有很大帮助
    - navigation.tabs # 页面上方的标签页
    - navigation.tracking # 页面滚动时，导航栏高亮当前页面
    - navigation.sections # 使导航栏分块
    # - navigation.expand # 默认展开导航
    # - navigation.prune # 只渲染当前页面的导航
    - toc.follow # 滚动的时候侧边栏自动跟随
    - navigation.top # 返回顶部按钮
    - search.suggest # 补全建议
    - search.highlight # 搜索结果高亮
    - navigation.footer # 页脚提示下一章
    - content.code.copy # 代码段上的赋值按钮

  custom_dir: overrides

#[Plugins]
plugins:
  # Translation plugin
  - i18n:
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true
          site_name: Robotics and AI Lab, SDNU
          nav_translations:
            介绍: Introduction

            竞赛目录: Contest Category
            中国机器人及人工智能大赛: CRAIC
            国际青年人工智能大赛: IYAIC
            机器人世界杯中国赛: RoboCup China Open
            机器人世界杯: RoboCup
            全国大学生机器人科技创新交流营暨机器人大赛: Robotics Innovation Camp by CYL


            教学资源: Learning Resource
            编程基础: Programming Basics
            理论基础: Theoretical Basics
            实用软件基础: Practical Software Basics

            成员风采: Elegant Demeanour

            历届获奖: Previous Awards

            其他: Others
            有趣的东西: Something Interesting
  # Search plugin
  - search:
      lang:
        - zh
        - en
  # Minify html, speed up the loading speed
  - minify:
      minify_html: true
  - git-revision-date-localized

extra_javascript:
  # 使用mathjax进行数学公式渲染
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - admonition # 那些提醒
  - footnotes # 脚注
  - toc
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.arithmatex: # latex支持
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true # 显示行号
      use_pygments: true # 代码高亮
      pygments_lang_class: true
      auto_title: true # 显示编程语言名称
      linenums_style: pymdownx-inline # 行号样式,防止复制的时候复制行号
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences